version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - REDIS_URL=${REDIS_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - .:/app
    command: >
      sh -c "flask db upgrade && gunicorn -w 4 -k gevent -b 0.0.0.0:8080 app:app"

# flask run --host=0.0.0.0 --port=8080
# 실제 production 환경에서는 gunicorn을 사용하는 것이 좋다.
# gunicorn -w 4 -k gevent -b 0.0.0.0:8080 app:app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"