apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app-template.fullname" . }}-post-install-job
  namespace: {{ include "app-template.fullname" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: post-install-job
          image: curlimages/curl:latest
          env:
            - name: RELEASE_NAME
              value: {{ include "app-template.fullname" . }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              curl -X POST -H "Content-Type: application/json" \
              -d '{"release_name": "{{ include "app-template.fullname" . }}", "status": "first-deployment-complete"}' \
              https://webhook.site/66c9e4e9-24b0-47f2-bf5b-af193ce5558c
      restartPolicy: OnFailure
