apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: {{ include "app-template.fullname" . }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: koo0833@naver.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
