apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "create-projects.fullname" . }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
    verbs:
      - create
      - patch
      - get
      - apply
