apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "create-projects.fullname" . }}-rb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ include "create-projects.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "create-projects.fullname" . }}
  apiGroup: rbac.authorization.k8s.io