apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "create-projects.fullname" . }}
  namespace: {{ include "create-projects.fullname" . }}
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    ci-event:
      endpoint: /
      method: POST
      port: "12000"