apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-role-binding
  namespace: {{ include "create-projects.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "create-projects.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: default