apiVersion: v1
data:
  argocd-server: aHR0cHM6Ly8xMC4xMDIuMTk1LjMwCg==
  password: eUhwaXVDRnA2VnRZc05nLQ==
  username: YWRtaW4K
kind: Secret
metadata:
  name: argocd-config
  namespace: {{ include "create-projects.fullname" . }}