apiVersion: v1
kind: Service
metadata:
  name: {{ include "create-projects.fullname" . }}
  namespace: {{ include "create-projects.fullname" . }}
  labels:
    {{- include "create-projects.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 12000
      protocol: TCP
      name: http
  selector:
    eventsource-name: {{ include "create-projects.fullname" . }}
